spring:
  application:
    name: helloService
    
server:
  port: 8081
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://52.86.121.106:8761/eureka/

logging:
  level:
    root: INFO
    com.netflix.hystrix.AbstractCommand: TRACE