spring:
  application:
    name: helloService
    
server:
  port: 8081
  
address:
  local: true
  
eureka:
  client:
    serviceUrl:
      #defaultZone: http://52.86.121.106:8761/eureka/
      defaultZone: http://ec2-52-86-121-106.compute-1.amazonaws.com:8761/eureka/
      #defaultZone: http://ec2-52-207-143-205.compute-1.amazonaws.com:8761/eureka/
    registryFetchIntervalSeconds: 1
    instanceInfoReplicationIntervalSeconds: 1
    initialInstanceInfoReplicationIntervalSeconds: 1
    eurekaServiceUrlPollIntervalSeconds: 1000
  instance:
    instanceEnabledOnit: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2  
      
logging:
  level:
    root: INFO
    com.netflix.hystrix.AbstractCommand: TRACE
